% Generated by sql-metadata command in blipkit_sql
:- discontiguous relation/2.
:- discontiguous attribute/3.
:- discontiguous unique/3.
%% IMPORTANT: unique/2 must be entered MANUALLY - cannot introspect

%% annotation_to_literal(?ANNOTATION_ROLE:integer, ?INDIVIDUAL:integer, ?VALUE:string, ?DATATYPE:string, ?LANGUAGE:string) is nondet
% maps to sql table
relation(annotation_to_literal, 5).
attribute(1, annotation_to_literal, annotation_role, integer).
attribute(2, annotation_to_literal, individual, integer).
attribute(3, annotation_to_literal, value, string).
attribute(4, annotation_to_literal, datatype, string).
attribute(5, annotation_to_literal, language, string).
%% annotation_to_resource(?ANNOTATION_ROLE:integer, ?A:integer, ?B:integer) is nondet
% maps to sql table
relation(annotation_to_resource, 3).
attribute(1, annotation_to_resource, annotation_role, integer).
attribute(2, annotation_to_resource, a, integer).
attribute(3, annotation_to_resource, b, integer).
%% concept_assertion(?CONCEPT:integer, ?INDIVIDUAL:integer) is nondet
% maps to sql table
relation(concept_assertion, 2).
attribute(1, concept_assertion, concept, integer).
attribute(2, concept_assertion, individual, integer).
%% data_role_assertion(?DATA_ROLE:integer, ?INDIVIDUAL:integer, ?VALUE:string, ?DATATYPE:string, ?LANGUAGE:string) is nondet
% maps to sql table
relation(data_role_assertion, 5).
attribute(1, data_role_assertion, data_role, integer).
attribute(2, data_role_assertion, individual, integer).
attribute(3, data_role_assertion, value, string).
attribute(4, data_role_assertion, datatype, string).
attribute(5, data_role_assertion, language, string).
%% individual_name(?ID:integer, ?NAME:string) is nondet
% maps to sql table
relation(individual_name, 2).
attribute(1, individual_name, id, integer).
attribute(2, individual_name, name, string).
%% object_role_assertion(?OBJECT_ROLE:integer, ?A:integer, ?B:integer) is nondet
% maps to sql table
relation(object_role_assertion, 3).
attribute(1, object_role_assertion, object_role, integer).
attribute(2, object_role_assertion, a, integer).
attribute(3, object_role_assertion, b, integer).

%% tbox_concept_inclusion(?SUB:integer, ?SUPER:integer, ?POSITIVE:bool) is nondet
% maps to sql table
relation(tbox_concept_inclusion, 3).
attribute(1, tbox_concept_inclusion, sub, integer).
attribute(2, tbox_concept_inclusion, super, integer).
attribute(3, tbox_concept_inclusion, positive, bool).
%% tbox_data_role_inclusion(?SUB:integer, ?SUPER:integer) is nondet
% maps to sql table
relation(tbox_data_role_inclusion, 2).
attribute(1, tbox_data_role_inclusion, sub, integer).
attribute(2, tbox_data_role_inclusion, super, integer).
%% tbox_name(?ID:integer, ?TYPE:integer, ?AUXILIARY:bool, ?FREQUENCY:integer, ?NAME:string) is nondet
% maps to sql table
relation(tbox_name, 5).
attribute(1, tbox_name, id, integer).
attribute(2, tbox_name, type, integer).
attribute(3, tbox_name, auxiliary, bool).
attribute(4, tbox_name, frequency, integer).
attribute(5, tbox_name, name, string).
%% tbox_object_role_inclusion(?SUB:integer, ?SUPER:integer) is nondet
% maps to sql table
relation(tbox_object_role_inclusion, 2).
attribute(1, tbox_object_role_inclusion, sub, integer).
attribute(2, tbox_object_role_inclusion, super, integer).
